#Mysql database configuration
spring.application.name=taskManagement
spring.datasource.url=JDBC:mysql://localhost:3306/taskManager
spring.datasource.username=vaibhaovk
spring.datasource.password=vaibhao
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server configuration
server.port=5004